# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Oral History (as) Data
email: dbecker@uidaho.edu
description: Lib-Static Oral History / Qualitative Interview Analysis ToolAnalyze and publish transcriptions with tagged csvs
 
baseurl: /oral-history-as-data
github_username: uidaholib


collections:
  transcripts:
      output: true
      permalink: /:collection/:name

defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
      


# Build settings
markdown: kramdown
